server.port=9090
server.address=0.0.0.0
spring.application.name=stats-service

# PostgreSQL configuration
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${STATS_DB_URL:jdbc:postgresql://localhost:5433/stats}
spring.datasource.username=${STATS_DB_USER:postgres}
spring.datasource.password=${STATS_DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
