server:
  port: 0

spring:
  application:
    name: stats-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${STATS_DB_URL:jdbc:postgresql://localhost:5433/stats}
    username: ${STATS_DB_USER:postgres}
    password: ${STATS_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
