server.port=8080
spring.application.name=main-service
spring.config.import=optional:configserver:http://config-server:8888
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${MAIN_DB_URL:jdbc:postgresql://localhost:5434/main_db}
spring.datasource.username=${MAIN_DB_USER:postgres}
spring.datasource.password=${MAIN_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
stats-server.url=${STATS_SERVER_URL:http://localhost:9090}
comments.max-per-user-per-event=5
logging.level.ru.practicum=INFO
logging.level.org.springframework.web=INFO
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
grpc.client.collector.address=discovery:///collector
grpc.client.analyzer.address=discovery:///analyzer
grpc.client.collector.address=discovery:///collector
grpc.client.analyzer.address=discovery:///analyzer
