/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.practicum.ewm.stats.avro;
@org.apache.avro.specific.AvroGenerated
public enum ActionTypeAvro implements org.apache.avro.generic.GenericEnumSymbol<ActionTypeAvro> {
  VIEW, REGISTER, LIKE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActionTypeAvro\",\"namespace\":\"ru.practicum.ewm.stats.avro\",\"symbols\":[\"VIEW\",\"REGISTER\",\"LIKE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
