/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.practicum.ewm.stats.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventSimilarityAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4604511759664049342L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventSimilarityAvro\",\"namespace\":\"ru.practicum.ewm.stats.avro\",\"fields\":[{\"name\":\"eventA\",\"type\":\"long\"},{\"name\":\"eventB\",\"type\":\"long\"},{\"name\":\"score\",\"type\":\"double\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<EventSimilarityAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventSimilarityAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventSimilarityAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventSimilarityAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventSimilarityAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventSimilarityAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventSimilarityAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventSimilarityAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventSimilarityAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long eventA;
  private long eventB;
  private double score;
  private java.time.Instant timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventSimilarityAvro() {}

  /**
   * All-args constructor.
   * @param eventA The new value for eventA
   * @param eventB The new value for eventB
   * @param score The new value for score
   * @param timestamp The new value for timestamp
   */
  public EventSimilarityAvro(java.lang.Long eventA, java.lang.Long eventB, java.lang.Double score, java.time.Instant timestamp) {
    this.eventA = eventA;
    this.eventB = eventB;
    this.score = score;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventA;
    case 1: return eventB;
    case 2: return score;
    case 3: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventA = (java.lang.Long)value$; break;
    case 1: eventB = (java.lang.Long)value$; break;
    case 2: score = (java.lang.Double)value$; break;
    case 3: timestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventA' field.
   * @return The value of the 'eventA' field.
   */
  public long getEventA() {
    return eventA;
  }


  /**
   * Sets the value of the 'eventA' field.
   * @param value the value to set.
   */
  public void setEventA(long value) {
    this.eventA = value;
  }

  /**
   * Gets the value of the 'eventB' field.
   * @return The value of the 'eventB' field.
   */
  public long getEventB() {
    return eventB;
  }


  /**
   * Sets the value of the 'eventB' field.
   * @param value the value to set.
   */
  public void setEventB(long value) {
    this.eventB = value;
  }

  /**
   * Gets the value of the 'score' field.
   * @return The value of the 'score' field.
   */
  public double getScore() {
    return score;
  }


  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(double value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new EventSimilarityAvro RecordBuilder.
   * @return A new EventSimilarityAvro RecordBuilder
   */
  public static ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder newBuilder() {
    return new ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder();
  }

  /**
   * Creates a new EventSimilarityAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventSimilarityAvro RecordBuilder
   */
  public static ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder newBuilder(ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder other) {
    if (other == null) {
      return new ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder();
    } else {
      return new ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder(other);
    }
  }

  /**
   * Creates a new EventSimilarityAvro RecordBuilder by copying an existing EventSimilarityAvro instance.
   * @param other The existing instance to copy.
   * @return A new EventSimilarityAvro RecordBuilder
   */
  public static ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder newBuilder(ru.practicum.ewm.stats.avro.EventSimilarityAvro other) {
    if (other == null) {
      return new ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder();
    } else {
      return new ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventSimilarityAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventSimilarityAvro>
    implements org.apache.avro.data.RecordBuilder<EventSimilarityAvro> {

    private long eventA;
    private long eventB;
    private double score;
    private java.time.Instant timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventA)) {
        this.eventA = data().deepCopy(fields()[0].schema(), other.eventA);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventB)) {
        this.eventB = data().deepCopy(fields()[1].schema(), other.eventB);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.score)) {
        this.score = data().deepCopy(fields()[2].schema(), other.score);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing EventSimilarityAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.practicum.ewm.stats.avro.EventSimilarityAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventA)) {
        this.eventA = data().deepCopy(fields()[0].schema(), other.eventA);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventB)) {
        this.eventB = data().deepCopy(fields()[1].schema(), other.eventB);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.score)) {
        this.score = data().deepCopy(fields()[2].schema(), other.score);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'eventA' field.
      * @return The value.
      */
    public long getEventA() {
      return eventA;
    }


    /**
      * Sets the value of the 'eventA' field.
      * @param value The value of 'eventA'.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder setEventA(long value) {
      validate(fields()[0], value);
      this.eventA = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventA' field has been set.
      * @return True if the 'eventA' field has been set, false otherwise.
      */
    public boolean hasEventA() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventA' field.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder clearEventA() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventB' field.
      * @return The value.
      */
    public long getEventB() {
      return eventB;
    }


    /**
      * Sets the value of the 'eventB' field.
      * @param value The value of 'eventB'.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder setEventB(long value) {
      validate(fields()[1], value);
      this.eventB = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventB' field has been set.
      * @return True if the 'eventB' field has been set, false otherwise.
      */
    public boolean hasEventB() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventB' field.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder clearEventB() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'score' field.
      * @return The value.
      */
    public double getScore() {
      return score;
    }


    /**
      * Sets the value of the 'score' field.
      * @param value The value of 'score'.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder setScore(double value) {
      validate(fields()[2], value);
      this.score = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'score' field has been set.
      * @return True if the 'score' field has been set, false otherwise.
      */
    public boolean hasScore() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'score' field.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder clearScore() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[3], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public ru.practicum.ewm.stats.avro.EventSimilarityAvro.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventSimilarityAvro build() {
      try {
        EventSimilarityAvro record = new EventSimilarityAvro();
        record.eventA = fieldSetFlags()[0] ? this.eventA : (java.lang.Long) defaultValue(fields()[0]);
        record.eventB = fieldSetFlags()[1] ? this.eventB : (java.lang.Long) defaultValue(fields()[1]);
        record.score = fieldSetFlags()[2] ? this.score : (java.lang.Double) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.time.Instant) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventSimilarityAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventSimilarityAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventSimilarityAvro>
    READER$ = (org.apache.avro.io.DatumReader<EventSimilarityAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










